Models/Configuration.cs
using System.ComponentModel.DataAnnotations;

namespace CadastroPessoa.Models
{
    public class Configuration
    {
        public const string UF_KEY = "operacao-uf";

        [Key]
        [Required]
        [MinLength(2), MaxLength(50)]
        public string Name { get; set; }

        [MaxLength(-1)]
        public string Value { get; set; }
    }
}

Models/Person.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CadastroPessoa.Models
{
    public class Person
    {
        private const string minLenMsg = "O campo '{0}' deveria ter no mínimo {1} caracteres.",
            maxLenMsg = "O campo '{0}' deveria ter no máximo {1} caracteres.",
            requiredMsg = "O campo '{0}' é obrigatório.",
            onlyNumbers = "O {0} deve conter apenas números.";

        [Required(ErrorMessage = requiredMsg)]
        [MinLength(5, ErrorMessage = minLenMsg), MaxLength(150, ErrorMessage = maxLenMsg)]
        [Display(Name = "Nome")]
        public string Name { get; set; }

        [Key]
        [Required(ErrorMessage = requiredMsg)]
        [MinLength(11, ErrorMessage = minLenMsg), MaxLength(11, ErrorMessage = maxLenMsg)]
        [RegularExpression(@"\d+", ErrorMessage = onlyNumbers)]
        public string Cpf { get; set; }

        [MinLength(6, ErrorMessage = minLenMsg), MaxLength(11, ErrorMessage = maxLenMsg)]
        [RegularExpression(@"\d+", ErrorMessage = onlyNumbers)]
        public string Rg { get; set; }

        [UIHint("UF")]
        [Required(ErrorMessage = requiredMsg)]
        [MinLength(2, ErrorMessage = minLenMsg), MaxLength(3, ErrorMessage = maxLenMsg)]
        public string Uf { get; set; }

        [Required(ErrorMessage = requiredMsg)]
        [DataType(DataType.Date, ErrorMessage = "O campo {0} está inválido.")]
        [Display(Name = "Data de Nascimento")]
        public DateTime DateOfBirth { get; set; }

        [Required(ErrorMessage = requiredMsg)]
        [DataType(DataType.Date)]
        public DateTime RegistrationDate { get; set; }

        [JsonIgnore]
        public virtual ICollection<Telephone> Telephones { get; set; } = new HashSet<Telephone>();
    }
}

Models/Telephone.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace CadastroPessoa.Models
{
    public class Telephone
    {
        private const string minLenMsg = "O campo '{0}' deveria ter no mínimo {1} caracteres.",
            maxLenMsg = "O campo '{0}' deveria ter no máximo {1} caracteres.",
            requiredMsg = "O campo '{0}' é obrigatório.",
            onlyNumbers = "O {0} deve conter apenas números.";

        [Required(ErrorMessage = requiredMsg)]
        [RegularExpression(@"^\d{2,3}$", ErrorMessage = "O DDD deve conter apenas números.")]
        [MinLength(2, ErrorMessage = minLenMsg), MaxLength(3, ErrorMessage = maxLenMsg)]
        public string DDD { get; set; }

        [Key]
        [Display(Name = "Número")]
        [Required(ErrorMessage = requiredMsg)]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"\d+", ErrorMessage = onlyNumbers)]
        [MinLength(8, ErrorMessage = minLenMsg), MaxLength(10, ErrorMessage = maxLenMsg)]
        public string Number { get; set; }

        public string PersonCpf { get; set; }

        [JsonIgnore]
        public virtual Person Person { get; set; }
    }
}

Models/TelephoneAddModelView.cs
using System.Collections.Generic;

namespace CadastroPessoa.Models
{
    public class TelephoneAddModelView
    {
        public string Cpf { get; set; }

        public Telephone Telephone { get; set; }

        public ICollection<Telephone> Telephones { get; set; }

        public TelephoneAddModelView()
        {
        }

        public TelephoneAddModelView(string cpf, ICollection<Telephone> telephones)
        {
            this.Cpf = cpf;
            this.Telephones = telephones;
            this.Telephone = new Telephone();
        }
    }
}

Controllers/ConsultController.cs
using CadastroPessoa.Code;
using CadastroPessoa.Data;
using CadastroPessoa.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace CadastroPessoa.Controllers
{
    public class ConsultController : BaseController
    {
        public ConsultController(ApplicationContext context)
            : base(context)
        {
        }

        /// <summary>
        /// View principal
        /// </summary>
        public IActionResult Index(
            [FromQuery]int page = 0,
            [FromQuery]int count = 15,
            [FromQuery]string filterBy = null,
            [FromQuery]string filterWith = null)
        {
            List<Person> model = context.GetListFromDb<Person>(page, count, filterBy, filterWith);

            return View(model);
        }
    }
}

Controllers/HomeController.cs
using CadastroPessoa.Data;
using Microsoft.AspNetCore.Mvc;

namespace CadastroPessoa.Controllers
{
    public class HomeController : BaseController
    {
        public HomeController(ApplicationContext context) : base(context)
        {
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>@ViewData["Title"] - CadastroPessoa</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/font-awesome.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CadastroPessoa</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Register" asp-action="Index">Registrar Pessoa</a></li>
                    <li><a asp-area="" asp-controller="Consult" asp-action="Index">Consultar</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="navbar-link" asp-controller="Register" asp-action="Config">Configurações <i class="fa fa-cog"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - CadastroPessoa</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.3.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
    </environment>

    <script type="text/javascript" src="~/lib/moment/min/moment.min.js"></script>
    <script type="text/javascript" src="~/lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
    <script type="text/javascript" src="~/js/datetimepicker-pt-br.js"></script>
    <link rel="stylesheet" href="~/lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Msg.cshtml
@if (ViewData["Message"] != null)
{
    string msg = (string)ViewData["Message"];
    MessageType type = (MessageType)ViewData["MessageType"];
    <div class="alert @type.GetBootstrapAlertEquivalent() alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @msg
    </div>
}